### PR TITLE
Add cnfa example

### PR DESCRIPTION
**Pull request by DavidVentura**
Per https://github.com/cntools/cnfa/issues/17, add an example of using `cnfa` on Android.

### CODE REVIEW

**Comment by dreua** [comment]
You can now rebase your prs on master to fix the ci.

**Comment by DavidVentura** [comment]
Cool, have rebased

**Comment by cnlohr** [comment]
This is still failing CI.  Any chance you can troubleshoot that before I accept?

**Comment by DavidVentura** [comment]
Before, the CI was broken on some `apt-get` issues - now it's unable to find a header.

I had the same error, and found the necessary header at `-I$(NDK)/sysroot/usr/include/android` in my local NDK. In the PR, I've added an include path which does not seem to work.

I'll try to replicate this NDK setup

**Comment by cnlohr** [comment]
Thank you.

**Comment by DavidVentura** [comment]
Had the wrong include path :upside_down_face:

**Comment by cnlohr** [comment]
This is insufficient for older SDKs, please include both include paths, not just altering it.

**Comment by DavidVentura** [comment]
I think the Github UI made the diff confusing, I've not removed any path, just added a new one.
I've flipped the order so the diff is clearer

**Comment by DavidVentura** [comment]
Ah, I think I get it; I've added the other path as well

**Comment by cnlohr** [comment]
I know a little annoying to ask now - can you make it so like pressing something triggers the sound?  So it doesn't always run?  Ram Jamming a loud eeeeeee is bit annoying for a simple test.

**Pull request merged**
